import express from 'express';
import auth from '../middleware/auth.js';
import roleCheck from '../middleware/roleCheck.js';

import {
  getAssignedRequests,
  updateRequestStatus,
  getReports,
} from '../controllers/labStaffController.js';

const router = express.Router();

// All lab staff routes require authentication and 'labstaff' role
router.use(auth, roleCheck('labstaff'));

// @route   GET /api/labstaff/requests
// @desc    View lab test requests assigned to this staff member
router.get('/requests', getAssignedRequests);

// @route   PUT /api/labstaff/requests/:id/status
// @desc    Update request status (e.g., to 'completed' or 'reported') and attach result
router.put('/requests/:id/status', updateRequestStatus);

// @route   GET /api/labstaff/reports
// @desc    View reports generated by this staff (optional)
router.get('/reports', getReports);

export default router;